app:
  name: nyc-taxi-demand-revenue-lakehouse
  timezone: America/New_York

storage:
  raw_path: data/raw
  bronze_path: data/bronze
  silver_path: data/silver
  gold_path: data/gold

sources:
  nyc_tlc_base_url: https://d37ci6vzurychx.cloudfront.net/trip-data
  taxi_zone_lookup_url: https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv
  source_name_trips: nyc_tlc_yellow_trips
  source_name_zones: nyc_tlc_taxi_zone_lookup

processing:
  default_start_month: 2024-01
  default_end_month: 2024-03
  incremental_state_file: data/raw/_state/processed_months.json
  max_reasonable_trip_hours: 8
  max_reasonable_trip_speed_mph: 80

quality:
  accepted_payment_types: [1,2,3,4,5,6]
  accepted_rate_codes: [1,2,3,4,5,6,99]
